export const SET_ATTRIBUTES = 'SET_ATTRIBUTES';
export const FETCH_CHARACTERS_FAILED = 'FETCH_CHARACTERS_FAILED';
export const FETCH_CHARACTERS_START = 'FETCH_CHARACTER_START';
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';

export const FETCH_CHARACTER_FAILED = 'FETCH_CHARACTER_FAILED';


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
